name: Auto Assign Reviewers
on:
  pull_request:
    types: [opened]
jobs:
  assign:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Auto-assign reviewers
        uses: kentaro-m/auto-assign-action@v1.2.0
        with:
          configuration-path: .github/auto_assign_config.yml
      - name: Fallback Reviewer Assignment
        if: failure()
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-reviewer kodurunani